docs/DeveloperGuide.adoc
Update user stories based on the targeted audiences: Traveler and Businessman
=> Documentation: Update user stories

src/main/java/seedu/address/logic/commands/AddCommand.java, src/main/java/seedu/address/logic/commands/ClearCommand.java, src/main/java/seedu/address/logic/commands/DeleteCommand.java, src/main/java/seedu/address/logic/commands/EditCommand.java, src/main/java/seedu/address/logic/commands/ExitCommand.java, src/main/java/seedu/address/logic/commands/FindCommand.java, src/main/java/seedu/address/logic/commands/HistoryCommand.java, src/main/java/seedu/address/logic/commands/ListCommand.java, src/main/java/seedu/address/logic/commands/RedoCommand.java, src/main/java/seedu/address/logic/commands/SelectCommand.java, src/main/java/seedu/address/logic/commands/UndoCommand.java, src/main/java/seedu/address/logic/parser/AddressBookParser.java
Reverts CS2103JAN2018-T15-B4/main#3
=> Revert "Logic: added shorthand commands"

docs/DeveloperGuide.adoc
Reverts CS2103JAN2018-T15-B4/main#4
=> Revert "Documentation: Update user stories"

docs/DeveloperGuide.adoc
Reverts CS2103JAN2018-T15-B4/main#7
=> Revert "Revert "Documentation: Update user stories""

src/main/java/seedu/address/logic/commands/AddCommand.java, src/main/java/seedu/address/logic/commands/ClearCommand.java, src/main/java/seedu/address/logic/commands/DeleteCommand.java, src/main/java/seedu/address/logic/commands/EditCommand.java, src/main/java/seedu/address/logic/commands/ExitCommand.java, src/main/java/seedu/address/logic/commands/FindCommand.java, src/main/java/seedu/address/logic/commands/HistoryCommand.java, src/main/java/seedu/address/logic/commands/ListCommand.java, src/main/java/seedu/address/logic/commands/RedoCommand.java, src/main/java/seedu/address/logic/commands/SelectCommand.java, src/main/java/seedu/address/logic/commands/UndoCommand.java, src/main/java/seedu/address/logic/parser/AddressBookParser.java
Reverts CS2103JAN2018-T15-B4/main#6
=> Revert "Revert "Logic: added shorthand commands""

src/main/java/seedu/address/commons/util/StringUtil.java, src/test/java/seedu/address/commons/util/StringUtilTest.java, src/test/java/systemtests/FindCommandSystemTest.java
=> Find Persons by partial words

docs/UserGuide.adoc
=> Documentation: Find Persons by partial words

src/main/java/seedu/address/MainApp.java, src/main/java/seedu/address/logic/Logic.java, src/main/java/seedu/address/logic/LogicManager.java, src/main/java/seedu/address/logic/parser/CalendarViewStateParser.java, src/main/java/seedu/address/model/CalendarEvent.java, src/main/java/seedu/address/ui/AnchorPaneNode.java, src/main/java/seedu/address/ui/CalendarView.java, src/main/java/seedu/address/ui/CalendarViewPanel.java, src/main/java/seedu/address/ui/MainWindow.java, src/main/resources/view/BrowserPanel.fxml, src/main/resources/view/CalendarView.fxml, src/main/resources/view/Extensions.css, src/main/resources/view/MainWindow.fxml, src/test/java/guitests/guihandles/MainWindowHandle.java, src/test/java/seedu/address/logic/LogicManagerTest.java, src/test/java/seedu/address/ui/BrowserPanelTest.java, src/test/java/seedu/address/ui/CommandBoxTest.java, src/test/java/systemtests/AddressBookSystemTest.java, src/test/java/systemtests/HelpCommandSystemTest.java
- displays a calendar view
- no functionality added yet
- browser panel disabled for now
=> Calendar View Feature

data/addressbook.xml, docs/DeveloperGuide.adoc, docs/UserGuide.adoc, src/main/java/seedu/address/logic/commands/AddPictureCommand.java, src/main/java/seedu/address/logic/parser/AddPictureCommandParser.java, src/main/java/seedu/address/logic/parser/CliSyntax.java
Updated developer and user guide to reflect slight change in syntax for addpicture.
Changed parser of addpicture
=> Fixes issue #70

data/addressbook.xml, src/main/java/seedu/address/logic/commands/AddTagCommand.java, src/main/java/seedu/address/logic/parser/AddTagCommandParser.java, src/main/java/seedu/address/logic/parser/AddressBookParser.java, src/main/java/seedu/address/model/person/Person.java
Allows a user to add tags to an existing contact, instead of using the edit function which forces users to input all existing tags again
=> Add Tag feature - Issue #74 

src/main/java/seedu/address/logic/parser/AddTagCommandParser.java, src/test/java/seedu/address/logic/commands/AddTagCommandTest.java, src/test/java/seedu/address/logic/parser/AddTagCommandParserTest.java
Also improved parser of AddTag command, to recognize invalid tags
=> Issue #79, added tests for AddTag command

src/main/java/seedu/address/logic/commands/FindCommand.java, src/main/java/seedu/address/logic/parser/FindCommandParser.java, src/main/java/seedu/address/model/tag/TagContainsKeywordsPredicate.java, src/test/data/XmlSerializableAddressBookTest/typicalAddressBook.xml, src/test/java/seedu/address/logic/commands/FindCommandTest.java, src/test/java/seedu/address/logic/parser/AddressBookParserTest.java, src/test/java/seedu/address/logic/parser/FindCommandParserTest.java, src/test/java/seedu/address/model/tag/TagContainsKeywordsPredicateTest.java, src/test/java/seedu/address/testutil/TypicalPersons.java, src/test/java/systemtests/AddressBookSystemTest.java, src/test/java/systemtests/FindCommandSystemTest.java
=> Find Command: able to find by name and tag

docs/DeveloperGuide.adoc, docs/UserGuide.adoc
=> Docs: Update Find Command feature and v2.0 features

docs/UserGuide.adoc
=> Docs: Update Convert Command result

data/addressbook.xml, src/main/java/seedu/address/ui/CalendarView.java, src/main/resources/view/MainWindow.fxml
Added:
- welcome message
- current date
- click-to-return function to return to current date (by clicking on current date)
=> Debugging UI Layout

collated/functional/CYX28.md, collated/functional/dezhanglee.md, collated/functional/jill858.md, collated/functional/x3tsunayh.md, collated/test/x3tsunayh.md, docs/AboutUs.adoc, src/main/java/seedu/address/logic/commands/AddEventCommand.java, src/main/java/seedu/address/logic/commands/ExportCommand.java, src/main/java/seedu/address/model/EventBook.java, src/main/java/seedu/address/model/Model.java, src/main/java/seedu/address/model/ModelManager.java, src/main/java/seedu/address/model/event/Datetime.java, src/main/java/seedu/address/model/event/UniqueEventList.java, src/main/java/seedu/address/model/event/exceptions/DuplicateEventException.java, src/main/java/seedu/address/storage/XmlEventBookStorage.java, src/test/java/seedu/address/logic/commands/CommandTestUtil.java, src/test/java/seedu/address/logic/commands/ExportCommandTest.java, src/test/java/seedu/address/logic/parser/AddEventCommandParserTest.java, src/test/java/seedu/address/storage/XmlEventBookStorageTest.java, src/test/java/seedu/address/testutil/EventBookBuilder.java, src/test/java/seedu/address/testutil/TypicalEvents.java
=> Bug Fixing

src/main/java/seedu/address/MainApp.java, src/main/java/seedu/address/commons/core/Config.java, src/main/java/seedu/address/commons/events/ui/GoogleContactNameEvent.java, src/main/java/seedu/address/commons/events/ui/JumpToCalendarRequestEvent.java, src/main/java/seedu/address/logic/commands/JumpToCommand.java, src/main/java/seedu/address/logic/parser/AddressBookParser.java, src/main/java/seedu/address/logic/parser/JumpToCommandParser.java, src/main/java/seedu/address/logic/parser/ParserUtil.java, src/main/java/seedu/address/model/UserPrefs.java, src/main/java/seedu/address/model/event/Datetime.java, src/main/java/seedu/address/model/util/SampleDataUtil.java, src/main/java/seedu/address/storage/XmlAdaptedPerson.java, src/main/java/seedu/address/ui/CalendarView.java, src/main/java/seedu/address/ui/MainWindow.java, src/test/java/seedu/address/commons/core/ConfigTest.java, src/test/java/seedu/address/logic/parser/FindEventCommandParserTest.java, src/test/java/seedu/address/logic/parser/GoogleCommandParserTest.java, src/test/java/seedu/address/logic/parser/JumpToCommandParserTest.java
Addresses issues #125 and #129
=> JumpToCommand + Bug Fixing

docs/DeveloperGuide.adoc, docs/UserGuide.adoc, src/main/java/seedu/address/logic/commands/FindCommand.java, src/main/java/seedu/address/logic/parser/FindCommandParser.java, src/main/java/seedu/address/model/person/AddressContainsKeywordsPredicate.java, src/main/java/seedu/address/model/person/PhoneContainsKeywordsPredicate.java, src/test/java/seedu/address/logic/parser/FindCommandParserTest.java, src/test/java/seedu/address/model/person/AddressContainsKeywordsPredicateTest.java, src/test/java/seedu/address/model/person/PhoneContainsKeywordsPredicateTest.java, src/test/java/seedu/address/model/tag/TagContainsKeywordsPredicateTest.java
=> Update find command: Find by phone and by address

docs/DeveloperGuide.adoc, docs/UserGuide.adoc, docs/team/jill858.adoc
=> Docs: Update Portfolio

src/main/java/seedu/address/commons/util/DateUtil.java, src/main/java/seedu/address/commons/util/StringUtil.java, src/main/java/seedu/address/logic/commands/ConvertCommand.java, src/main/java/seedu/address/model/Currency.java, src/test/java/seedu/address/commons/util/DateUtilTest.java, src/test/java/seedu/address/commons/util/StringUtilTest.java, src/test/java/seedu/address/logic/commands/ConvertCommandTest.java, src/test/java/seedu/address/model/CurrencyTest.java
Added API - fixer.io to convert currency from one to another
=> Command: Update Convert Currency to include API
